project_id = "gwwqfoplhhtyjkrhazbt"

[functions.google-places]
verify_jwt = true

[functions.mapbox-geocoding]
verify_jwt = true

[functions.tripadvisor-photos]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false