project_id = "gwwqfoplhhtyjkrhazbt"

[functions.google-places]
verify_jwt = false

[functions.mapbox-geocoding]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.tripadvisor-photos]
verify_jwt = false